name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        scala: [JVM2_12, JVM2_13, JVM3]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1

    - name: Download test executor
      run: |
        ./make_harness.sh

    - uses: olafurpg/setup-scala@v12
      with:
        java-version: adopt@1.11
    - name: Compile and test
      run: |
        sbt "core${{matrix.scala}}/test" "codeGen${{matrix.scala}}/test" "e2e${{matrix.scala}}/test" "e2e${{matrix.scala}}/test:runMain scalapb.validate.ScalaHarness"

    - name: Formatting
      run: |
        sbt scalafmtCheck test:scalafmtCheck scalafmtSbtCheck

    - name: Run example project
      run: |
        cd example
        sbt run
  # Single final job for mergify.
  ci-passed:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - run: ':'
